name: Feature request / 功能建议
description: Suggest an improvement / 提交改进建议
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: need
    attributes:
      label: User need / 使用需求
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Suggested solution / 建议方案
    validations:
      required: true
